import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import MainLayout from "../components/MainLayout";
import AuthProvider from "../components/AuthProvider";
import ScrollTop from "../components/ScrollTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <AuthProvider>
          <Navbar></Navbar>
          <MainLayout>{children}</MainLayout>
          <Footer></Footer>
          <ScrollTop></ScrollTop>
        </AuthProvider>
      </body>
    </html>
  );
}
